rem @echo OFF
set status=0
set Current_STATION=55
set Pass_STATION=99


rem ----------------------------------------------- CONFIG MODIFY THIS  ONLY --------------------------------------------------
rem Babylon TestTrabking Starting Addr=0x4F, 48 Bytes totally
rem EEPROM Address::: TBD = 0x51, 4K Focus Tuning =0x53, 4K MTF Recheck VCM =0x55, 4K Blemish =0x57, 8L IR+Mic=0x59, 8L 4K=0x5B 
rem EEPROM Data   ::: PASS =99, Fail=FF and Others
rem Test Station 9 PASS, 0x49=99, Test Station 9 Fail 0x49=others
rem ----------------------------------------------- DONOT MODIFY BELOW THIS POINT  --------------------------------------------


rem ====================================================================================================
rem  DOS command %DATE% --> "31/01/2015 ", with a Blank at the end 
rem  DOS coomad %Time% ---> "TUE16:23:22:27"
rem  DOS command %Date%%Time% --> "31/01/2015 TUE16:23:22:27"
rem  
rem  Data Structure needed:  310115+SeqNum,  Byte1:Month+Date, Byte2:Y+MSB SeqNum  in mfgstr
rem  where XX is for the Test Flow Test Tracking, following characters are for serial number tracking  
rem
rem  wifimac.txt generated by DateTimeGen.bat
rem ====================================================================================================



rem ========================================
rem === Go test mode for EEPROM access  ====
rem ========================================
lvreg testxu write A 8
lvreg eeprom write 55 99



exit %status%





