@echo OFF
set status=0
set Last_STATION=99

echo
rem ----------------------------------------------- CONFIG MODIFY THIS  ONLY --------------------------------------------------
rem Babylon TestTrabking Starting Addr=0x4F, 48 Bytes totally
rem EEPROM Address::: TBD = 0x51, 4K Focus Tuning =0x53, 4K MTF Recheck VCM =0x55, 4K Blemish =0x57, 8L IR+Mic=0x59, 8L 4K=0x5B 
rem                               IR Focus        =0x63, IR MTF Recheck     = 0x65, IR Blemsh = 0x67
rem EEPROM Data   ::: PASS =99, Fail=FF and Others, 
rem Test Station 9 PASS, 0x49=99, Test Station 9 Fail 0x49=others
rem ----------------------------------------------- DONOT MODIFY BELOW THIS POINT  --------------------------------------------


rem ====================================================================================================
rem  DOS command %DATE% --> "31/01/2015 ", with a Blank at the end 
rem  DOS coomad %Time% ---> "TUE16:23:22:27"
rem  DOS command %Date%%Time% --> "31/01/2015 TUE16:23:22:27"
rem  
rem  Data Structure needed:  XX_31012015_16232227, 20 Characters lenght, stored in mfgstr
rem  where XX is for the Test Flow Test Tracking, following characters are for serial number tracking  
rem
rem  wifimac.txt generated by DateTimeGen.bat
rem ====================================================================================================

rem =================================================
rem ====  Go test mode for EEPROM access  ===========
rem =================================================

set m1=m1
set m3=m3
set m5=m5
set m7=m7
set m9=m9
set mB=mB
set mD=mD
set mF=mF
set mG=mG
set mH=mH
set mI=mI
 if exist "%m1%" (
del %m1%
)
 if exist "%m3%" (
del %m3%
)
 if exist "%m5%" (
del %m5%
)
 if exist "%m7%" (
del %m7%
)
 if exist "%m9%" (
del %m9%
)
 if exist "%mB%" (
del %mB%
)
 if exist "%mD%" (
del %mD%
)
 if exist "%mF%" (
del %mF%
)
 if exist "%mG%" (
del %mG%
)
 if exist "%mH%" (
del %mH%
)
 if exist "%mI%" (
del %mI%
)

lvreg testxu write A 8

lvreg eeprom read 51 >>%m1%
lvreg eeprom read 53 >>%m3%
lvreg eeprom read 55 >>%m5%
lvreg eeprom read 57 >>%m7%
lvreg eeprom read 59 >>%m9%
lvreg eeprom read 5B >>%mB%
lvreg eeprom read 5D >>%mD%
lvreg eeprom read 5F >>%mF%
lvreg eeprom read 63 >>%mG%
lvreg eeprom read 65 >>%mH%
lvreg eeprom read 67 >>%mI%


set /p rm1=<%m1%
set /p rm3=<%m3%
set /p rm5=<%m5%
set /p rm7=<%m7%
set /p rm9=<%m9%
set /p rmB=<%mB%
set /p rmD=<%mD%
set /p rmF=<%mF%
set /p rmG=<%mG%
set /p rmH=<%mH%
set /p rmI=<%mI%


del wifimac.txt
rem echo 3:%rm3%_5:%rm5%_7:%rm7%_9:%rm9%_B:%rmB%_D:%rmD%_F:%rmF%_IR1:%rmG%_IR2:%rmH%_IR3:%rmI%
echo 3_%rm3:~2,2%X5_%rm5:~2,2%X7_%rm7:~2,2%X9_%rm9:~2,2%XB_%rmB:~2,2%XD_%rmD:~2,2%XF_%rmF:~2,2%X1_%rmG:~2,2%X2_%rmH:~2,2%X3_%rmI:~2,2% >wifimac.txt


rem ====================================================================================================
rem   wifimac.txt, wifimac.in are hard coded in TDEBT-Analyzer.exe, DO NOT change their file names !!!
rem   
rem ====================================================================================================

COPY TestTrackChkAll.in wifimac.in 
TDEBT-Analyzer.exe wifimac.in wifimac.txt
COPY wifimac.out TestTrackchkAll.out

call status.bat

exit %status%


