@echo OFF
set status=0
set Last_STATION=99


rem ----------------------------------------------- CONFIG MODIFY THIS  ONLY -----------------------------------------------
rem TBD = 1 4K Focus Tuning =3, 4K MTF Recheck VCM =5, 4K Blemish =7, 8L IR+Mic=9, 8L 4K=B 
rem PASS =A, Fail=F
rem 9A = Test Station 9 PASS, 9F = Test Station 9 Fail
rem ----------------------------------------------- DONOT MODIFY BELOW THIS POINT  -----------------------------------



rem ====================================================================================================
rem  DOS command %DATE% --> "31/01/2015 ", with a Blank at the end 
rem  DOS coomad %Time% ---> "TUE16:23:22:27"
rem  DOS command %Date%%Time% --> "31/01/2015 TUE16:23:22:27"
rem  
rem  Data Structure needed:  XX_31012015_16232227, 20 Characters lenght, stored in mfgstr
rem  where XX is for the Test Flow Test Tracking, following characters are for serial number tracking  
rem
rem  wifimac.txt generated by DateTimeGen.bat
rem ====================================================================================================

rem =================================================
rem ====  Go test mode for EEPROM access  ===========
rem =================================================
lvreg testxu write A 8

set PMTT_fileVar=%testtracking.txt

rem ===== 2014.8.1 ==========

lvreg eeprom read 53 >%PMTT_fileVar%
set /p pmts_readval=<%PMTT_fileVar%
if "%pmts_readval%" == "%Last_STATION%" (
goto EndPASS
) 


rem ==================================================================
rem ==================================================================
:ReturnNG
set status=1
rem start HP6612Com7_0V.bat
rem exit 1
rem ==================================================================
goto SetNGFlag

:EndPASS

:SetNGFlag
lvreg eeprom write 55 11


exit %status%