rem @echo OFF
set status=0
set Current_STATION=B
set Pass_STATION=A

rem ----------------------------------------------- CONFIG MODIFY THIS  ONLY -----------------------------------------------
rem TBD = 1 4K Focus Tuning =3, 4K MTF Recheck VCM =5, 4K Blemish =7, 8L IR+Mic=9, 8L 4K=B , FW Update = D
rem PASS =A, Fail=F
rem 9A = Test Station 9 PASS, 9F = Test Station 9 Fail
rem ----------------------------------------------- DONOT MODIFY BELOW THIS POINT  -----------------------------------


rem ====================================================================================================
rem  DOS command %DATE% --> "31/01/2015 ", with a Blank at the end 
rem  DOS coomad %Time% ---> "TUE16:23:22:27"
rem  DOS command %Date%%Time% --> "31/01/2015 TUE16:23:22:27"
rem  
rem  Data Structure needed:  310115+SeqNum,  Byte1:Month+Date, Byte2:Y+MSB SeqNum  in mfgstr
rem  where XX is for the Test Flow Test Tracking, following characters are for serial number tracking  
rem
rem  wifimac.txt generated by DateTimeGen.bat
rem ====================================================================================================


rem set Str=3A

lvreg testxu write A 8
lvreg eeprom read 5B
lvreg eeprom write 5B 99



exit %status%





