@echo OFF
set status=0
set Last_STATION=99

echo
rem ----------------------------------------------- CONFIG MODIFY THIS  ONLY --------------------------------------------------
rem Babylon TestTrabking Starting Addr=0x4F, 48 Bytes totally
rem EEPROM Address::: TBD = 0x51, 4K Focus Tuning =0x53, 4K MTF Recheck VCM =0x55, 4K Blemish =0x57, 8L IR+Mic=0x59, 8L 4K=0x5B 
rem EEPROM Data   ::: PASS =99, Fail=FF and Others, 
rem Test Station 9 PASS, 0x49=99, Test Station 9 Fail 0x49=others
rem ----------------------------------------------- DONOT MODIFY BELOW THIS POINT  --------------------------------------------


rem ====================================================================================================
rem  DOS command %DATE% --> "31/01/2015 ", with a Blank at the end 
rem  DOS coomad %Time% ---> "TUE16:23:22:27"
rem  DOS command %Date%%Time% --> "31/01/2015 TUE16:23:22:27"
rem  
rem  Data Structure needed:  XX_31012015_16232227, 20 Characters lenght, stored in mfgstr
rem  where XX is for the Test Flow Test Tracking, following characters are for serial number tracking  
rem
rem  wifimac.txt generated by DateTimeGen.bat
rem ====================================================================================================

rem =================================================
rem ====  Go test mode for EEPROM access  ===========
rem =================================================

set m1=m1
set m3=m3
set m5=m5
set m7=m7
set m9=m9
set mB=mB
set mD=mD
set mF=mF
 if exist "%m1%" (
del %m1%
)
 if exist "%m3%" (
del %m3%
)
 if exist "%m5%" (
del %m5%
)
 if exist "%m7%" (
del %m7%
)
 if exist "%m9%" (
del %m9%
)
 if exist "%mB%" (
del %mB%
)
 if exist "%mD%" (
del %mD%
)
 if exist "%mF%" (
del %mF%
)

lvreg testxu write A 8

lvreg eeprom read 51 >>%m1%
lvreg eeprom read 53 >>%m3%
lvreg eeprom read 55 >>%m5%
lvreg eeprom read 57 >>%m7%
lvreg eeprom read 59 >>%m9%
lvreg eeprom read 5B >>%mB%
lvreg eeprom read 5D >>%mD%
lvreg eeprom read 5F >>%mF%


set /p rm1=<%m1%
set /p rm3=<%m3%
set /p rm5=<%m5%
set /p rm7=<%m7%
set /p rm9=<%m9%
set /p rmB=<%mB%
set /p rmD=<%mD%
set /p rmF=<%mF%


del wifimac.txt
echo S1:%rm1%_S3:%rm3%_S5:%rm5%_S7:%rm7%_S9:%rm9%_S11:%rmB%_S13:%rmD%_S15:%rmF% >wifimac.txt


rem ====================================================================================================
rem   wifimac.txt, wifimac.in are hard coded in TDEBT-Analyzer.exe, DO NOT change their file names !!!
rem   
rem ====================================================================================================

COPY TestTrackChkAll.in wifimac.in 
TDEBT-Analyzer.exe wifimac.in wifimac.txt
COPY wifimac.out TestTrackchkAll.out

call status.bat

exit %status%


