@Echo off
REM Please do not modify this file, this file is generated by c:\Program Files\Common Files\Logitech\EasyAVRuntimeEngine\UltimateControlCmd.exe
SET Status=1
SET ReturnCode=1
SET Message=
[E]: error result.
SET Headers=name1
SET Values=N/A
SET LowLimit=0.0
SET UpLimit=10.0
SET TargetLimit=10.0
SET LogFile=test.log
SET VarResultSummary=
