@Echo off
REM Please do not modify this file, this file is generated by c:\Program Files (x86)\Common Files\Logitech\EasyAVRuntimeEngine\UltimateScpiCmd.exe
SET Status=0
SET ReturnCode=0
SET Message=Ok!
SET Headers=USBVoltage
SET Values=
SET LowLimit=0.0
SET UpLimit=5.0
SET TargetLimit=5.0
SET LogFile=D:\Bolide_4Corner_Color_PB1\UltimateScpiCmd.log
SET VarResultSummary=
